apiVersion: v1
kind: Service
metadata:
  name: interaction-service
  labels:
    app: interaction-service
spec:
  type: ClusterIP
  selector:
    app: interaction-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8200
