apiVersion: apps/v1
kind: Deployment
metadata:
  - name: consul
spec:
  replicas: 1
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
        - name: consul
          image: consul:1.15
          args:
            - "agent"
            - "-server"
            - "-bootstrap-expect=1"
            - "-ui"
            - "-bind=0.0.0.0"
            - "-client=0.0.0.0"
          ports:
            - containerPort: 8500
            - containerPort: 8600
              protocol: UDP
            