apiVersion: apps/v1
kind: Deployment
metadata:
  name: story-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: story-service
  template:
    metadata:
      labels:
        app: story-service
    spec:
      containers:
        - name: story-service
          image: gcr.io/my-blog-454607/story-service:latest
          env:
          - name: DATABASE_URL
            value: "mysql://thanh:123@tcp(mysql:3306)/story_db?charset=utf8&parseTime=True&loc=Local"
          ports:
          - containerPort: 8080