name: Deploy user-service to GKE

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      USE_GKE_GCLOUD_AUTH_PLUGIN: True

    steps:
      # Checkout mã nguồn
      - name: Checkout source code
        uses: actions/checkout@v3

      # Xác thực với Google Cloud
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # Cài đặt Google Cloud SDK
      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: my-blog-454607

      # Cài đặt gke-gcloud-auth-plugin bằng apt-get
      - name: Install gke-gcloud-auth-plugin
        run: |
          # Thêm GPG key của Google Cloud
          curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | sudo apt-key add -
          # Thêm Google Cloud CLI repository
          echo "deb https://packages.cloud.google.com/apt google-cloud-cli main" | sudo tee -a /etc/apt/sources.list.d/google-cloud-sdk.list
          # Cập nhật danh sách gói và cài đặt plugin
          sudo apt-get update
          sudo apt-get install -y google-cloud-cli-gke-gcloud-auth-plugin

      # Cấu hình Docker để đẩy image lên GCR
      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker gcr.io --quiet

      # Kết nối với GKE cluster
      - name: Connect to GKE cluster
        run: |
          gcloud container clusters get-credentials my-cluster \
            --zone asia-southeast1-a \
            --project my-blog-454607

      # Build và push Docker image
      - name: Build & Push Docker Image
        run: |
          docker build -t gcr.io/my-blog-454607/user-service:latest ./user-service
          docker push gcr.io/my-blog-454607/user-service:latest

      # Triển khai MySQL lên GKE
      - name: Deploy MySQL to GKE
        run: |
          kubectl apply -f k8s/mysql-configmap.yaml
          kubectl apply -f k8s/mysql-pv.yaml
          kubectl apply -f k8s/mysql-deployment.yaml
          kubectl apply -f k8s/mysql-service.yaml

      # Triển khai user-service lên GKE
      - name: Deploy user-service to GKE
        run: |
          kubectl apply -f k8s/user-service-deployment.yaml
          kubectl apply -f k8s/user-service-service.yaml

      # Kiểm tra trạng thái pods
      - name: Check Kubernetes status
        run: |
          kubectl get pods
          kubectl wait --for=condition=ready pod -l app=user-service --timeout=300s
          kubectl wait --for=condition=ready pod -l app=mysql --timeout=300s